### ISSUE TITLE
Make unlimited villain strength/influence possible

### ISSUE THREAD

**Issue by Faro1991** [Detailing-the-Realm/svnsea2e#24]
Again, as the title says.

GM wants to have a villain that has a strength/influence value greater than 10.

**Accenptance Criterium**
As was possible before, villain strength/influence can be switched to a numerical display that allows for values greater than 10. Wounds should still be calculated accordingly.

**Comment by psychoph** [comment]
This is something I have gone back and forth on. Because I use circles now I can't do infinite. I need a specific limit. I couldn't find anything in the books that set a maximum for strength and influence. 

Are you really going to have a villain with a strength of more than 20? That would be up to 20 dice rolled in combat, which no player could match. Players will max out at 10 for trait+skill and then whatever bonus dice they might get. 

I am certainly willing to increase the number above ten, but I would prefer not to switch this back to a numeric field.

**Comment by Faro1991** [comment]
> Are you really going to have a villain with a strength of more than 20? That would be up to 20 dice rolled in combat, which no player could match. Players will max out at 10 for trait+skill and then whatever bonus dice they might get.

I mean, I'll admit that it might be a very specific use case, but yes, I do. I've got one module in my posession that is an (admittedly and intentionally) unfair Halloween-themed horror one shot for which the villain gets a strength of 6+[H] with a maximum of 14 and a starting influence of 2. As a workaround I'll probably just have the "missing" strength flow over into influence, but at least increasing the limit to 15 would work for me.

**Comment by psychoph** [comment]
I will increase it to 20 tonight and try to get a release out hopefully before your game.

**Comment by Faro1991** [comment]
Thanks! Even if you don't, I'll simply use my workaround and give her appropriate bonus dice as needed. But still thanks for considering OP villains :)
